version: '3.8'

networks:
  eureka-network:
    driver: bridge
services:

  eureka-server:
    image: springcloud/eureka
    container_name: eureka-server
    ports:
      - "8761:8761"
    networks:
      - eureka-network

  config-server:
    image: config-server:latest
    container_name: config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8088:8088"
    networks:
      - eureka-network
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/

  api-gateway:
    image: api-gateway:latest
    container_name: api-gateway
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
      - config-server
    networks:
      - eureka-network
    ports:
      - "8060:8060"

  service-registry:
    image: service-registry:latest
    container_name: service-registry
    build:
      context: ./service-registry
      dockerfile: Dockerfile
    ports:
      - "8762:8762"
    #    environment:
    #      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    #    depends_on:
    #      - eureka-server
    networks:
      - eureka-network


  employee-service:
    image: employee-service:latest
    container_name: employee-service
    build:
      context: ./employee-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-network
    ports:
      - "8082:8082"




  department-service:
    image: department-service:latest
    container_name: department-service
    build:
      context: ./department-service
      dockerfile: Dockerfile
    environment:
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://eureka-server:8761/eureka/
    depends_on:
      - eureka-server
    networks:
      - eureka-network
    ports:
      - "8081:8081"

#networks:
#  eureka-network:
#    driver: bridge

